_BASE_: univs_R50_bs8_video_200queries_c1+univs.yaml
MODEL:
  BACKBONE: 
    FREEZE_AT: 5
    NAME: "build_resnet_backbone"
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs16_f2_video_c1+univs.pth'
  META_ARCHITECTURE: "UniVS_Prompt_LongVideo"
  SEM_SEG_HEAD:
    FROZEN_PIXEL_DECODER: True  #  input_proj &transformer.encoder
    FROZEN_MASK_CONVS: False
    FROZEN_PREDICTOR: False
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
    NUM_OBJECT_QUERIES: 200
    CLASS_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    REID_WEIGHT: 0.5
    CLASS_WEIGHT_MATCHER: 2.0
    MASK_WEIGHT_MATCHER: 5.0
    DICE_WEIGHT_MATCHER: 5.0
    REID_WEIGHT_MATCHER: 0.5
  UniVS:
    NUM_POS_QUERIES: 10
    VISUAL_PROMPT_PIXELS_PER_IMAGE: 32
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: True
    PROMPT_AS_QUERIES: True
    VISUAL_PROMPT_TO_IMAGE_ENABLE: True
    TEXT_PROMPT_TO_IMAGE_ENABLE: True
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'sep'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
    DISABLE_LEARNABLE_QUERIES_SA1B: False
DATASETS:
  DATASET_RATIO: 
   # OD & IS
  - 0.25  # lvis
  - 0.35  # ovis 42k
  - 0.25  # ytvis21 90k
  # VSS & VPS
  - 0.25  # panoptic coco
  - 0.5   # vipseg 85k
  # Ref
  - 0.35 # refcoco
  - 0.35 # ref-ytvos
  # SOT & VOS
  - 0.25  # sa1b
  - 0.25  # ytvos18
  - 0.35  # mose
  - 0.5   # burst
  TRAIN: 
  # OD & IS
  - "lvis_v1_train_video"    # 100k (shared categories with burst)
  - "ovis_train"             # 35k  (551 videos)
  - "ytvis_2021_train"       # 90k  (2679 videos)
  # VPS
  - "coco_panoptic_train"
  - "vipseg_panoptic_train"  # 85k
  # Ref
  - "rvos_refcoco-mixed"     # 5.5k images
  - "rvos-refytb-train"      # 3.5k (3469 videos)
  # SOT & VOS
  - "sa_1b_train_250k_1"     # 250k
  - "sot_ytbvos18_train"     # 90k (3471 videos)
  - "mots_mose_train"        #
  - "mots_burst_train"       # 
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_WINDOE_NUM: 5
  SAMPLING_FRAME_VIDEO_NUM: 10
  SAMPLING_FRAME_RANGE: 40
  MIN_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (148000, 162000)
  MAX_ITER: 177000  # 0.5x for bs=4 (148000, 162000, 177000)
  CHECKPOINT_PERIOD: 2500
TEST:
  DETECTIONS_PER_IMAGE: 35
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2
OUTPUT_DIR: output/univs_prompt_R50_bs16_f5w5v10_video_2x_200queries_c1+univs+casa_prompt_sa_frozenbb+pixelenc/