_BASE_: univs_R50_bs8_coco+sa1b.yaml
MODEL:
  WEIGHTS: 'pretrained/m2f_panseg/model_final_94dc52.pth'
  META_ARCHITECTURE: "BoxVIS_VideoMaskFormer"
  MASK_FORMER:
      NUM_OBJECT_QUERIES: 200
      CLASS_WEIGHT: 5.0
      MASK_WEIGHT: 3.0
      DICE_WEIGHT: 3.0
      REID_WEIGHT: 0.5
DATASETS:
  DATASET_RATIO: 
  - 1.0
  - 1.0
  TRAIN: 
  - "coco_panoptic_train"
  - "sa_1b_train_250k_1"
INPUT:
  SAMPLING_FRAME_NUM: 1
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (80000, )
  MAX_ITER: 100000  # 1x for bs=16
OUTPUT_DIR: output/univs_R50_bs16_sa1b+coco_LSGaug_0.5xft_wbg_200queries_max100/