_BASE_: univs_R50_bs8_coco+sa1b_200queries_b.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs24_f1_sa1b+coco_2x_200queries_b+casa.pth'
  SEM_SEG_HEAD:
    NUM_CLASSES: 40
  MASK_FORMER:
      NUM_OBJECT_QUERIES: 200
      CLASS_WEIGHT: 5.0
      MASK_WEIGHT: 3.0
      DICE_WEIGHT: 3.0
      REID_WEIGHT: 0.25
      TEST:
        SEMANTIC_ON: False
        INSTANCE_ON: False
        PANOPTIC_ON: True
        OVERLAP_THRESHOLD: 0.8
        OBJECT_MASK_THRESHOLD: 0.05
        STABILITY_SCORE_THRESH: 0.
  UniVS:
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: False
    PROMPT_AS_QUERIES: False
    VISUAL_PROMPT_TO_IMAGE_ENABLE: False
    TEXT_PROMPT_TO_IMAGE_ENABLE: False
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'none'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
  BoxVIS:
    TEST:
      NUM_FRAMES: 3
      NUM_FRAMES_WINDOW: 5
      CLIP_STRIDE: 1
      LSJ_AUG_ENABLED: True
      ZERO_SHOT_INFERENCE: False
      TRACKER_TYPE: 'minvis'
      APPLY_CLS_THRES: 0.25
DATASETS:
  DATASET_RATIO:
    # - 0.5  # coco 118k
    - 0.5  # ovis 42k
    - 1.0  # ytvis21 90k
    - 1.0  # vipseg 85k
  TRAIN:
    # - "coco_panoptic_train"    # 117k  Note: max(H, W) >= 480
    - "ovis_train"             # 35k  (551 videos)
    - "ytvis_2021_train"       # 90k  (2679 videos)
    - "vipseg_panoptic_train"  # 85k
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 3
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 480
SOLVER:
  BASE_LR: 0.00005
  IMS_PER_BATCH: 2
  STEPS: (160000, 180000)
  MAX_ITER: 200000  # 0.5x for bs=8
TEST:
  DETECTIONS_PER_IMAGE: 25
OUTPUT_DIR: output/univs_prompt_R50_bs16_f3_vis+vps_LSGaug_200queries_dataloader_iter_100k_b/
