_BASE_: univs_R50_bs8_coco+sa1b_200queries_b+seem.yaml
MODEL:
  BACKBONE: 
    FREEZE_AT: 5
    NAME: "build_resnet_backbone"
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs24_f1_sa1b+coco_2x_200queries_b+seem+casa.pth'
  SEM_SEG_HEAD:
    NUM_CLASSES: 40
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderSEEM"
    NUM_OBJECT_QUERIES: 200
    CLASS_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    REID_WEIGHT: 0.5
    CLASS_WEIGHT_MATCHER: 2.0
    MASK_WEIGHT_MATCHER: 5.0
    DICE_WEIGHT_MATCHER: 5.0
    REID_WEIGHT_MATCHER: 0.5
  UniVS:
    NUM_POS_QUERIES: 30
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: True
    PROMPT_AS_QUERIES: False
    VISUAL_PROMPT_TO_IMAGE_ENABLE: False
    TEXT_PROMPT_TO_IMAGE_ENABLE: False
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'none'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
  BoxVIS:
    TEST:
      NUM_FRAMES: 3
      NUM_FRAMES_WINDOW: 5
      CLIP_STRIDE: 1
      LSJ_AUG_ENABLED: True
      ZERO_SHOT_INFERENCE: False
      TRACKER_TYPE: 'minvis'
      APPLY_CLS_THRES: 0.25
DATASETS:
  DATASET_RATIO: 
  # OD & IS
  - 0.25  # lvis
  - 0.35  # ovis 42k
  - 0.25  # ytvis21 90k
  # VSS & VPS
  - 0.25  # panoptic coco
  - 0.5   # vipseg 85k
  # Ref
  - 0.35 # refcoco
  - 0.35 # ref-ytvos
  # SOT & VOS
  - 0.25  # sa1b
  - 0.25  # ytvos18
  - 0.35  # mose
  - 0.5   # burst
  TRAIN: 
  # OD & IS
  - "lvis_v1_train_video"    # 100k (shared categories with burst)
  - "ovis_train"             # 35k  (551 videos)
  - "ytvis_2021_train"       # 90k  (2679 videos)
  # VPS
  - "coco_panoptic_train"
  - "vipseg_panoptic_train"  # 85k
  # Ref
  - "rvos_refcoco-mixed"     # 5.5k images
  - "rvos-refytb-train"      # 3.5k (3469 videos)
  # SOT & VOS
  - "sa_1b_train_250k_1"     # 250k
  - "sot_ytbvos18_train"     # 90k (3471 videos)
  - "mots_mose_train"        #
  - "mots_burst_train"       # 
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 480
SOLVER:
  BASE_LR: 0.00005
  IMS_PER_BATCH: 2
  STEPS: (295000, 324500)
  MAX_ITER: 354000  # 1.25x for bs=8
TEST:
  DETECTIONS_PER_IMAGE: 25
OUTPUT_DIR: output/univs_prompt_R50_bs8_f2_vis+vps_LSGaug_200queries_dataloader_iter_200k_b+seem+casa/
