_BASE_: Base.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 5
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs/univs_prompt_swinb_bs8_f4_video_2x_200queries_c1+univs+casa_prompt+sa_frozenbb.pth'
  META_ARCHITECTURE: "UniVS_Prompt_LongVideo"
  SEM_SEG_HEAD:
    FROZEN_PIXEL_DECODER: True
    FROZEN_MASK_CONVS: False
    FROZEN_PREDICTOR: False
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
    NUM_OBJECT_QUERIES: 200
    CLASS_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    REID_WEIGHT: 0.25
    CLASS_WEIGHT_MATCHER: 2.0
    MASK_WEIGHT_MATCHER: 5.0
    DICE_WEIGHT_MATCHER: 5.0
    REID_WEIGHT_MATCHER: 0.25
  UniVS:
    NUM_POS_QUERIES: 20
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: True
    PROMPT_AS_QUERIES: True
    VISUAL_PROMPT_TO_IMAGE_ENABLE: True
    TEXT_PROMPT_TO_IMAGE_ENABLE: True
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'sep'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
    DISABLE_LEARNABLE_QUERIES_SA1B: False
  BoxVIS:
    TEST:
      NUM_FRAMES_WINDOW: 5
      CLIP_STRIDE: 1
      LSJ_AUG_ENABLED: True
      TRACKER_TYPE: 'minvis'
      APPLY_CLS_THRES: 0.25
DATASETS:
  DATASET_RATIO: 
  # OD & IS
  - 0.25  # lvis
  - 0.35  # ovis 42k
  - 0.25  # ytvis21 90k
  # VSS & VPS
  - 0.25  # panoptic coco
  - 0.5   # vipseg 85k
  # Ref
  - 0.35 # refcoco
  - 0.35 # ref-ytvos
  # SOT & VOS
  - 0.25  # sa1b
  - 0.25  # ytvos18
  - 0.35  # mose
  - 0.5   # burst
  TRAIN: 
  # OD & IS
  - "lvis_v1_train_video"    # 100k (shared categories with burst)
  - "ovis_train"             # 35k  (551 videos)
  - "ytvis_2021_train"       # 90k  (2679 videos)
  # VPS
  - "coco_panoptic_train"
  - "vipseg_panoptic_train"  # 85k
  # Ref
  - "rvos_refcoco-mixed"     # 5.5k images
  - "rvos-refytb-train"      # 3.5k (3469 videos)
  # SOT & VOS
  - "sa_1b_train_250k_1"     # 250k
  - "sot_ytbvos18_train"     # 90k (3471 videos)
  - "mots_mose_train"        #
  - "mots_burst_train"       # 
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 4
  SAMPLING_FRAME_WINDOE_NUM: 4
  SAMPLING_FRAME_VIDEO_NUM: 7
  SAMPLING_FRAME_RANGE: 40
  MIN_SIZE_TEST: 800
SOLVER:
  BASE_LR: 0.00005
  IMS_PER_BATCH: 2
  STEPS: (162000, )
  MAX_ITER: 177000  # 2x: (324k, 354k) for bs=8; (162k, 177k) for bs=16, (108k, 118k) for bs=24
TEST:
  DETECTIONS_PER_IMAGE: 35
OUTPUT_DIR: output/univs_prompt_swinb_bs8_f4w4v7_longvideo_2x_200queries_c1+univs+casa_prompt+sa_frozenbb+pixelenc/