_BASE_: univs_R50_bs8_coco+sa1b+ref_200queries_c1.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs24_f1_sa1b+coco_2x_200queries_c1+casa.pth'
  META_ARCHITECTURE: "UniVS_Prompt"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
    NUM_OBJECT_QUERIES: 200
    CLASS_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    REID_WEIGHT: 0.5
    CLASS_WEIGHT_MATCHER: 2.0
    MASK_WEIGHT_MATCHER: 5.0
    DICE_WEIGHT_MATCHER: 5.0
    REID_WEIGHT_MATCHER: 0.5
  UniVS:
    NUM_POS_QUERIES: 30
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: True
    PROMPT_AS_QUERIES: True
    VISUAL_PROMPT_TO_IMAGE_ENABLE: True
    TEXT_PROMPT_TO_IMAGE_ENABLE: True
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'sep'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
    DISABLE_LEARNABLE_QUERIES_SA1B: False
DATASETS:
  DATASET_RATIO: 
  - 1.0
  - 1.0
  - 1.0
  TRAIN: 
  - "coco_panoptic_train"
  - "rvos_refcoco-mixed"
  - "sa_1b_train_250k_1"
INPUT:
  SAMPLING_FRAME_NUM: 1
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (108000, )
  MAX_ITER: 118000  # 4x for bs=48
OUTPUT_DIR: output/v2/univs_prompt_R50_bs48_f1_sa1b+coco+ref_1x_200queries_c1+univs+casa_prompt_sa/