_BASE_: ../univs_prompt/univs_prompt_r50_16f.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs_v2_cvpr/univs_swinb_stage3_f7_wosquare_ema.pth'
  BoxVIS:
    EMA_ENABLED: True
    TEST:
      CLIP_STRIDE: 5
  UniVS:
    TEST:
      VIDEO_UNIFIED_INFERENCE_ENABLE: True
      CUSTOM_VIDEOS_ENABLE: False
DATASETS:
  TEST: ("hurricane_vidnet_vis",)

  # NOTE: HurricaneVidNet dataset ONLY supports VSS
  # TRAIN: ("HurricaneVidNet_vss_video_train",)
  # TEST: ("HurricaneVidNet_vss_video_test",)
INPUT:
  SAMPLING_FRAME_NUM: 5
  MIN_SIZE_TEST: 720
TEST:
  DETECTIONS_PER_IMAGE: 50
OUTPUT_DIR: output/hurricane_results 